### ISSUE TITLE
pyinotify.AsyncioNotifier raises Exceptions when used

### ISSUE THREAD

**Issue by optimuspaul** [seb-m/pyinotify#107]
I'm using python3 and trying out the AsyncioNotifier, for every event that comes in I get this exception.

```
xception in callback <bound method AsyncioNotifier.handle_read of <pyinotify.AsyncioNotifier object at 0x7f1af339c2b0>>()
handle: Handle(<bound method AsyncioNotifier.handle_read of <pyinotify.AsyncioNotifier object at 0x7f1af339c2b0>>, ())
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 39, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.4/dist-packages/pyinotify.py", line 1599, in handle_read
    self.handle_read_callback(self)
  File "/usr/local/lib/python3.4/dist-packages/pyinotify.py", line 910, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/usr/local/lib/python3.4/dist-packages/pyinotify.py", line 622, in __call__
    stripped_mask = event.mask - (event.mask & IN_ISDIR)
AttributeError: 'AsyncioNotifier' object has no attribute 'mask'
```

Looks like event isn't what we think it is.

**Comment by optimuspaul** [comment]
nevermind, I was using it wrong. I was passing in my `ProcessEvent` object as the callback and not the default_proc_fun.
