### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor when launching in daemon mode.

### ISSUE THREAD

**Issue by Wobak** [seb-m/pyinotify#118]
Hi,

I am migrating my server to a new one, and I've decided to go from scratch on the new server.
Unfortunately, unable to get it running...
First I created a dedicated user and used a simple git clone and chown. 
Then I just tried the pip install sickrage, which installed it in the /usr/lib/python2.7/site-packages/sickrage directory.

It all remains the same.

Problem is as follow : 

```
# sickrage
Downloading pip ...
Downloading: /usr/lib/python2.7/site-packages/requirements/get-pip.py Bytes: 1412744                                                                       Installing pip ...0%]
Exception:
Traceback (most recent call last):
  File "/tmp/tmpfMhPhG/pip.zip/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/tmp/tmpfMhPhG/pip.zip/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/tmp/tmpfMhPhG/pip.zip/pip/basecommand.py", line 272, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/tmp/tmpfMhPhG/pip.zip/pip/req/req_install.py", line 213, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/tmp/tmpfMhPhG/pip.zip/pip/req/req_install.py", line 67, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/tmp/tmpfMhPhG/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2985, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '')
Cleaning up downloaded pip files
Patching SiCKRAGE SSL Context
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 272, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 213, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 67, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2985, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', u'')
Checking for required SiCKRAGE packages, please stand by ...
Checking for upgradable SiCKRAGE packages, please stand by ...
20:52:50 INFO::MAIN::SiCKRAGE VERSION:[6.0.28] CONFIG:[/usr/lib/python2.7/site-packages/config.ini]
20:52:50 INFO::TORNADO::Starting SiCKRAGE web server on [http://x.x.x.x:8081/]
20:52:50 INFO::TORNADO::Launching browser window 
```

This actually works despite the 2 exceptions : 

```
# ss -natp | grep 8081
LISTEN     0      128          *:8081                     *:*                   users:(("sickrage",pid=13546,fd=7))
```

But if I add --daemon : 

```
# sickrage --daemon
Downloading pip ...
Downloading: /usr/lib/python2.7/site-packages/requirements/get-pip.py Bytes: 1412744                                                                       Installing pip ...0%]
Exception:
Traceback (most recent call last):
  File "/tmp/tmpGzCoP5/pip.zip/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/tmp/tmpGzCoP5/pip.zip/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/tmp/tmpGzCoP5/pip.zip/pip/basecommand.py", line 272, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/tmp/tmpGzCoP5/pip.zip/pip/req/req_install.py", line 213, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/tmp/tmpGzCoP5/pip.zip/pip/req/req_install.py", line 67, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/tmp/tmpGzCoP5/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2985, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', '')
Cleaning up downloaded pip files
Patching SiCKRAGE SSL Context
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 282, in run
    wheel_cache
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 272, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 213, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 67, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2985, in parse
    raise ValueError("No requirements found", s)
ValueError: ('No requirements found', u'')
Checking for required SiCKRAGE packages, please stand by ...
Checking for upgradable SiCKRAGE packages, please stand by ...
```

I get back to my prompt, but : 

```
# ss -natp | grep 8081
```

and most importantly : 

```
time:           Tue 19 Jan 2016 08:32:20 PM CET
cmdline:        /usr/bin/python /usr/bin/sickrage --daemon
uid:            0 (root)
abrt_version:   2.1.11
dso_list:       python-libs-2.7.5-34.el7.x86_64
event_log:
executable:     /usr/bin/sickrage
hostname:       -------------------- obfuscated
kernel:         3.10.0-327.4.4.el7.x86_64
last_occurrence: 1453233305
pid:            12329
runlevel:       N 3
username:       root

backtrace:
:i18n.py:80:write:IOError: [Errno 9] Bad file descriptor
:
:Traceback (most recent call last):
:  File "/usr/bin/sickrage", line 11, in <module>
:    sys.exit(main())
:  File "/usr/lib/python2.7/site-packages/sickrage/__init__.py", line 759, in main
:    traceback.print_tb(exc_traceback)
:  File "/usr/lib64/python2.7/traceback.py", line 67, in print_tb
:    '  File "%s", line %d, in %s' % (filename, lineno, name))
:  File "/usr/lib64/python2.7/traceback.py", line 13, in _print
:    file.write(str+terminator)
:  File "/usr/lib/python2.7/site-packages/hachoir_core/i18n.py", line 80, in write
:    self.device.write(text)
:IOError: [Errno 9] Bad file descriptor
:
:Local variables in innermost frame:
:text: '  File "/usr/lib/python2.7/site-packages/sickrage/__init__.py", line 755, in main\n'
:self: <hachoir_core.i18n.UnicodeStdout object at 0x29145d0>
```

Every tutorial I've been reading sounds pretty straightforward but it seems I can't get it working. Did I miss something huge ? (I actually had to install some packages that were missing during gcc compile of some of the pip packages, such as openssl-devel or libffi-devel). 

Thanks for your help,

**Comment by Wobak** [comment]
I think I was in the wrong github project, sorry for that.
