### ISSUE TITLE
OSError: No such file or directory.

### ISSUE THREAD

**Issue by ghost** [seb-m/pyinotify#132]
May be related to https://github.com/seb-m/pyinotify/issues/76.
Same thing happening to me, only for files. I sync down from S3 to watched dir by aws cli "aws sync ...". Apparently aws sync first writes file with dodgy `.D15e7984` filename extention.  Notifier dies seeing this file and is restarted by my while loop. Meanwhile aws removes the extention and Notifies processes the new file without error:

```
2016-10-14 06:01:00,029 - ERROR - Restarted Notifier. Error was: [Errno 2] No such file or directory: '/var/www/html/sites/default/files/css/css_RPj9uAk5WuFHnq_9BitJUXUNtTv9cpprq_e6P8HMRhA.css.gz.D15e7984'
2016-10-14 06:01:00,031 - INFO - <Event cookie=312 dir=False mask=0x80 maskname=IN_MOVED_TO name=css_RPj9uAk5WuFHnq_9BitJUXUNtTv9cpprq_e6P8HMRhA.css.gz path=/var/www/html/sites/default/files/css pathname=/var/www/html/sites/default/files/css/css_RPj9uAk5WuFHnq_9BitJUXUNtTv9cpprq_e6P8HMRhA.css.gz wd=1845 >
```

Time between the two above events is 2 ms...
Is the fix in Issue #76 is supposed to cover it?
My code:

```
...
    # watched events
    mask = pyinotify.IN_CLOSE_WRITE | pyinotify.IN_MOVED_TO

    # watch manager
    wm = pyinotify.WatchManager()
    wm.add_watch(watched_dir, mask, rec=True, auto_add=True)
    eh = MyHandler(bucket=bucket, s3path=s3path)
    notifier = pyinotify.Notifier(wm, eh)

    while True:
        try:
            notifier.loop(daemonize=True, pid_file=False)
        except Exception, e:   # pyinotify.NotifierError
            logging.error( 'Restarted Notifier. Error was: %s' % str(e) )
...
```

Trace (different file, but from same session, again dodgy extention `.4A07cA3c`):

```
Traceback (most recent call last):
  File "./s3sync.py", line 215, in <module>
    main()
  File "./s3sync.py", line 209, in main
    notifier.loop(daemonize=False, pid_file=False)
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 1390, in loop
    self.process_events()
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 1287, in process_events
    self._default_proc_fun(revent)
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 924, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 650, in __call__
    return self.process_default(event)
  File "./s3sync.py", line 60, in process_default
    os.stat(str(event.pathname)).st_size != 0
OSError: [Errno 2] No such file or directory: '/var/www/html/sites/default/files/js/js_bK0Bh86hv9S9RTNCPTzdQd-62jQhnWDq7lIUvtvi1wQ.js.4A07cA3c'
```

**Comment by ghost** [comment]
Apparently, from trace, I had to check if file exists first in MyHandler, before everything:
`if os.path.isfile(event.pathname):`
Closing.
