### ISSUE TITLE
freebsd Unknown mask 0x00000030

### ISSUE THREAD

**Issue by davidgarvey** [seb-m/pyinotify#146]
Does pyinotify support freebsd?
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/fn_virt/lib/python2.7/site-packages/pyinotify.py", line 2386, in <module>
    command_line()
  File "/root/fn_virt/lib/python2.7/site-packages/pyinotify.py", line 2382, in command_line
    notifier.loop(callback=cb_fun)
  File "/root/fn_virt/lib/python2.7/site-packages/pyinotify.py", line 1390, in loop
    self.process_events()
  File "/root/fn_virt/lib/python2.7/site-packages/pyinotify.py", line 1283, in process_events
    revent = self._sys_proc_fun(raw_event)  # system processings
  File "/root/fn_virt/lib/python2.7/site-packages/pyinotify.py", line 639, in __call__
    raise ProcessEventError("Unknown mask 0x%08x" % stripped_mask)
__main__.ProcessEventError: Unknown mask 0x00000030

**Comment by davidgarvey** [comment]
dependency, Linux ≥ 2.6.13 ;(

**Comment by davidgarvey** [comment]
freebsd not supported.
