### ISSUE TITLE
Syntax Error while importing pyinotify in Python 3.5.3

### ISSUE THREAD

**Issue by akumar38** [seb-m/pyinotify#171]
I have installed pyinotify. While importing pyinotify, i'm encountering a syntax error.

>>> import pyinotify
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 896, in _find_spec
File "<frozen importlib._bootstrap_external>", line 1152, in find_spec
File "<frozen importlib._bootstrap_external>", line 1128, in _get_spec
File "<frozen importlib._bootstrap_external>", line 1109, in _legacy_get_spec
File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
File "<frozen importlib._bootstrap_external>", line 546, in spec_from_file_location
File "/root/anaconda3/lib/python3.5/site-packages/pyinotify-0.9.6-py3.5.egg/pyinotify.py", line 179
except IOError, err:
              ^
SyntaxError: invalid syntax

can anyone suggest how to eliminate this error.

**Comment by lromanov** [comment]
It's python 2 exception handling syntax, should be `except IOError as err:` instead.
Maybe you can make a pull request for that?
