### ISSUE TITLE
Notifier.loop method can fail by exception

### ISSUE THREAD

**Issue by grubberr** [seb-m/pyinotify#76]
I monitor pretty big tree of files with pyinotify
and time to time Notifier.loop method fails with such exception

```
Traceback (most recent call last):
  File "/opt/hosting/scripts/fsmon.py", line 315, in <module>
    notifier.loop(callback=on_loop)
  File "/opt/hosting/software/python/lib/python2.7/site-packages/pyinotify.py", line 1400, in loop
    self.process_events()
  File "/opt/hosting/software/python/lib/python2.7/site-packages/pyinotify.py", line 1291, in process_events
    revent = self._sys_proc_fun(raw_event)  # system processings
  File "/opt/hosting/software/python/lib/python2.7/site-packages/pyinotify.py", line 662, in __call__
    return meth(event)
  File "/opt/hosting/software/python/lib/python2.7/site-packages/pyinotify.py", line 734, in process_IN_CREATE
    for name in os.listdir(created_dir):
OSError: [Errno 2] No such file or directory: '/home/mongo7/public_html/ognom/cache/db_cache/e11d28c667b05853606c9459b023f81d'
```

**Comment by maxt1000** [comment]
Same thing happening to me, only for files, synced down to watched dir by aws cli "aws sync ...". Apparently aws sync first writes file with dodgy `.D15e7984` filename extention.  Notifier dies seeing this file and is restarted by my while loop. Meanwhile aws removed the extention and Notifies processes the file without error:
```
2016-10-14 06:01:00,029 - ERROR - Restarted Notifier. Error was: [Errno 2] No such file or directory: '/var/www/html/sites/default/files/css/css_RPj9uAk5WuFHnq_9BitJUXUNtTv9cpprq_e6P8HMRhA.css.gz.D15e7984'
2016-10-14 06:01:00,031 - INFO - <Event cookie=312 dir=False mask=0x80 maskname=IN_MOVED_TO name=css_RPj9uAk5WuFHnq_9BitJUXUNtTv9cpprq_e6P8HMRhA.css.gz path=/var/www/html/sites/default/files/css pathname=/var/www/html/sites/default/files/css/css_RPj9uAk5WuFHnq_9BitJUXUNtTv9cpprq_e6P8HMRhA.css.gz wd=1845 >
```
If this fix supposed to cover it?
